# Generated by Django 2.2.1 on 2019-10-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportnews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='schedule',
            field=models.DateTimeField(),
        ),
    ]
