# Generated by Django 2.2.1 on 2019-10-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportnews', '0002_auto_20191020_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='away_result',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='local_result',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
