# Generated by Django 2.2.1 on 2019-10-21 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportnews', '0005_auto_20191021_0633'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='standing',
            unique_together={('league', 'team')},
        ),
    ]
