# Generated by Django 2.2.1 on 2019-10-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportnews', '0006_auto_20191021_0636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'News'},
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.FileField(upload_to='logos/'),
        ),
    ]
